export default [
    {
        ignores: [".remember/**"],
    },
    {
        files: ["**/*.js", "**/*.jsx", "**/*.ts", "**/*.tsx", "**/*.mjs", "**/*.cjs", "**/*.vue"],
        rules: {
          "no-new-native-nonconstructor": ["error"],
          "no-constant-binary-expression": ["error"],
          "valid-typeof": ["error", {"requireStringLiterals": false}],
          "use-isnan": ["error", {"enforceForIndexOf": false, "enforceForSwitchCase": true}],
          "require-atomic-updates": ["error", {"allowProperties": false}],
          "no-useless-call": ["error"],
          "no-useless-backreference": ["error"],
          "no-use-before-define": ["error"],
          "no-unused-expressions": ["error", {"allowTernary": false, "enforceForJSX": false, "allowShortCircuit": false, "allowTaggedTemplates": false}],
          "no-unsafe-optional-chaining": ["error", {"disallowArithmeticOperators": false}],
          "no-unsafe-negation": ["error", {"enforceForOrderingRelations": false}],
          "no-unsafe-finally": ["error"],
          "no-unreachable-loop": ["error"],
          "no-unreachable": ["error"],
          "no-unmodified-loop-condition": ["error"],
          "no-unexpected-multiline": ["error"],
          "no-undef": ["error", {"typeof": false}],
          "no-this-before-super": ["error"],
          "no-template-curly-in-string": ["error"],
          "no-sparse-arrays": ["error"],
          "no-shadow-restricted-names": ["error"],
          "no-setter-return": ["error"],
          "no-self-compare": ["error"],
          "no-self-assign": ["error", {"props": true}],
          "no-script-url": ["error"],
          "no-return-await": ["error"],
          "no-redeclare": ["error", {"builtinGlobals": true}],
          "no-prototype-builtins": ["error"],
          "no-promise-executor-return": ["error", {"allowVoid": false}],
          "no-octal": ["error"],
          "no-obj-calls": ["error"],
          "no-new-symbol": ["error"],
          "no-new-require": ["error"],
          "no-negated-in-lhs": ["error"],
          "no-native-reassign": ["error"],
          "no-misleading-character-class": ["error"],
          "no-loss-of-precision": ["error"],
          "no-loop-func": ["error"],
          "no-iterator": ["error"],
          "no-irregular-whitespace": ["error", {"skipTemplates": false, "skipRegExps": false, "skipComments": false, "skipJSXText": false, "skipStrings": true}],
          "no-invalid-this": ["error", {"capIsConstructor": true}],
          "no-invalid-regexp": ["error"],
          "no-inner-declarations": ["error", "functions"],
          "no-import-assign": ["error"],
          "no-implied-eval": ["error"],
          "no-global-assign": ["error"],
          "no-func-assign": ["error"],
          "no-fallthrough": ["error", {"allowEmptyCase": false}],
          "no-extra-bind": ["error"],
          "no-ex-assign": ["error"],
          "no-eval": ["error", {"allowIndirect": false}],
          "no-eq-null": ["error"],
          "no-empty-pattern": ["error", {"allowObjectPatternsAsParameters": false}],
          "no-empty-character-class": ["error"],
          "no-duplicate-case": ["error"],
          "no-dupe-keys": ["error"],
          "no-dupe-else-if": ["error"],
          "no-dupe-class-members": ["error"],
          "no-dupe-args": ["error"],
          "no-delete-var": ["error"],
          "no-debugger": ["error"],
          "no-control-regex": ["error"],
          "no-constructor-return": ["error"],
          "no-constant-condition": ["error", {"checkLoops": true}],
          "no-const-assign": ["error"],
          "no-cond-assign": ["error", "except-parens"],
          "no-compare-neg-zero": ["error"],
          "no-class-assign": ["error"],
          "no-case-declarations": ["error"],
          "no-buffer-constructor": ["error"],
          "no-await-in-loop": ["error"],
          "no-async-promise-executor": ["error"],
          "handle-callback-err": ["error"],
          "guard-for-in": ["error"],
          "getter-return": ["error", {"allowImplicit": false}],
          "for-direction": ["error"],
          "constructor-super": ["error"],
          "consistent-return": ["error", {"treatUndefinedAsUnspecified": false}],
          "callback-return": ["error"],
          "array-callback-return": ["error", {"allowVoid": false, "checkForEach": false, "allowImplicit": false}],
        }
    }
];