tools:
    - name: eslint
      languages: [Javascript, TypeScript]
      extensions: [.js, .jsm, .jsx, .mjs, .ts, .tsx, .vue]
      files: []
    - name: lizard
      languages: [Go, Javascript, TypeScript]
      extensions: [.go, .js, .jsm, .jsx, .mjs, .ts, .tsx, .vue]
      files: []
    - name: opengrep
      languages: [Go, Javascript, TypeScript, YAML]
      extensions: [.env, .go, .js, .jsm, .jsx, .mjs, .ts, .tsx, .vue, .yaml, .yml]
      files: []
    - name: pmd
      languages: [Javascript, XML]
      extensions: [.js, .jsm, .jsx, .mjs, .pom, .vue, .wsdl, .xml, .xsl]
      files: []
    - name: trivy
      languages: [Go, JSON, Javascript, TypeScript, XML, YAML]
      extensions: [.env, .go, .js, .jsm, .json, .jsx, .mjs, .pom, .ts, .tsx, .vue, .wsdl, .xml, .xsl, .yaml, .yml]
      files: [.env, .env.dev, .env.development, .env.prod, .env.production, .env.staging, go.mod, package-lock.json, package.json, pnpm-lock.yaml, yarn.lock]
