codecov:
  require_ci_to_pass: true

coverage:
  status:
    project:
      default:
        target: 60%
        threshold: 5%
    patch:
      default:
        target: 80%
        threshold: 10%

ignore:
  - "cmd/**"
  - "**/*_test.go"
  - "**/mock_*.go"