package cli

import (
	"context"
	"fmt"
	"net"
	"os"
	"strings"
	"time"

	"github.com/spf13/cobra"
	"github.com/velasco-jp/nyx/internal/backends/nmap"
	"github.com/velasco-jp/nyx/internal/backends/system"
	"gopkg.in/yaml.v3"
)

var initOutput string

var initCmd = &cobra.Command{
	Use:   "init",
	Short: "Auto-detect your network and generate a starter spec",
	Long: `Discover local interfaces, RFC1918 routes, and live hosts via nmap ping sweep,
then write a nyx.yaml spec you can customize.`,
	Example: `  nyx init
  nyx init --output mynet.yaml`,
	RunE: func(cmd *cobra.Command, args []string) error {
		if err := nmap.CheckAvailable(); err != nil {
			return fmt.Errorf("nyx init requires nmap: %w", err)
		}

		out := os.Stdout
		if initOutput != "" {
			f, err := os.Create(initOutput)
			if err != nil {
				return fmt.Errorf("creating output file: %w", err)
			}
			defer f.Close()
			out = f
		}

		fmt.Fprintln(os.Stderr, "Detecting local interfaces...")
		localCIDRs, err := detectLocalCIDRs()
		if err != nil {
			return fmt.Errorf("detecting interfaces: %w", err)
		}
		if len(localCIDRs) == 0 {
			return fmt.Errorf("no RFC1918 interfaces found — are you connected to a network?")
		}

		var nets []initNet
		dur, _ := time.ParseDuration(timeout)
		if dur == 0 {
			dur = 300 * time.Second
		}

		for _, c := range localCIDRs {
			fmt.Fprintf(os.Stderr, "Scanning %s (polite mode, may take a moment)...\n", c.cidr)
			ctx, cancel := context.WithTimeout(context.Background(), dur)
			result, err := nmap.DiscoverWithOptions(ctx, c.cidr, nmap.PoliteScanOptions)
			cancel()

			hostCount := 0
			if err != nil {
				fmt.Fprintf(os.Stderr, "  warning: scan failed: %v (continuing with 0 hosts)\n", err)
			} else if result != nil {
				if v, ok := result.Observed["hosts_up"]; ok {
					switch n := v.(type) {
					case int:
						hostCount = n
					case float64:
						hostCount = int(n)
					}
				}
			}

			nets = append(nets, initNet{
				cidr:      c.cidr,
				gateway:   c.gateway,
				localIP:   c.localIP,
				hosts:     hostCount,
				ifaceName: c.ifaceName,
			})
			fmt.Fprintf(os.Stderr, "  → %d host(s) up\n", hostCount)
		}

		// Build spec YAML
		generatedSpec := buildInitSpec(nets)
		data, err := yaml.Marshal(generatedSpec)
		if err != nil {
			return fmt.Errorf("marshalling spec: %w", err)
		}

		header := "# Generated by nyx init — customize networks, policies, and assertions to match your intent.\n\n"
		_, err = fmt.Fprint(out, header+string(data))
		if err != nil {
			return err
		}

		if initOutput != "" {
			fmt.Fprintf(os.Stderr, "\nWrote spec to %s\n", initOutput)
			fmt.Fprintf(os.Stderr, "Next: review the file, then run: nyx audit --spec %s\n", initOutput)
		}
		return nil
	},
}

type initNet struct {
	cidr      string
	gateway   string
	localIP   string
	hosts     int
	ifaceName string
}

type localCIDR struct {
	cidr      string
	gateway   string
	localIP   string
	ifaceName string
}

// detectLocalCIDRs finds RFC1918 subnets the local machine has addresses in,
// using the routing table to find real gateways instead of guessing .1.
func detectLocalCIDRs() ([]localCIDR, error) {
	ifaces, err := net.Interfaces()
	if err != nil {
		return nil, err
	}

	// Build a map of subnet CIDR → gateway from the routing table.
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	routeGateways := map[string]string{}
	defaultGW := ""
	defaultGWMetric := -1
	if routes, err := system.GetRoutes(ctx); err != nil {
		fmt.Fprintf(os.Stderr, "warning: could not read routing table: %v (gateway detection will use defaults)\n", err)
	} else {
		for _, r := range routes {
			if isInvalidGW(r.Gateway) {
				continue
			}
			if r.Destination == "default" {
				// Keep the lowest-metric default route as the primary gateway.
				if defaultGWMetric < 0 || r.Metric < defaultGWMetric {
					defaultGW = r.Gateway
					defaultGWMetric = r.Metric
				}
				continue
			}
			routeGateways[r.Destination] = r.Gateway
		}
	}

	seen := map[string]bool{}
	var results []localCIDR

	for _, iface := range ifaces {
		if iface.Flags&net.FlagUp == 0 || iface.Flags&net.FlagLoopback != 0 {
			continue
		}
		addrs, err := iface.Addrs()
		if err != nil {
			fmt.Fprintf(os.Stderr, "warning: could not read addresses for %s: %v (skipping)\n", iface.Name, err)
			continue
		}
		for _, a := range addrs {
			ipNet, ok := a.(*net.IPNet)
			if !ok {
				continue
			}
			ip := ipNet.IP.To4()
			if ip == nil || !isRFC1918(ip) {
				continue
			}
			maskedIP := ip.Mask(ipNet.Mask)
			network := &net.IPNet{IP: maskedIP, Mask: ipNet.Mask}
			cidrStr := network.String()
			if seen[cidrStr] {
				continue
			}
			seen[cidrStr] = true

			// Use routing table gateway if known. For directly-connected subnets
			// the route table shows "On-link" as gateway, so check if the default
			// gateway falls within this subnet before falling back to .1.
			gw := routeGateways[cidrStr]
			if gw == "" && defaultGW != "" {
				if parsedGW := net.ParseIP(defaultGW); parsedGW != nil {
					if _, subnet, err := net.ParseCIDR(cidrStr); err == nil {
						if subnet.Contains(parsedGW) {
							gw = defaultGW
						}
					}
				}
			}
			if gw == "" {
				gw = guessGateway(maskedIP)
			}
			results = append(results, localCIDR{
				cidr:      cidrStr,
				gateway:   gw,
				localIP:   ip.String(),
				ifaceName: iface.Name,
			})
		}
	}
	return results, nil
}

// isVirtualIface returns true for host-only/NAT virtual adapters that have no
// real DNS server — VMware, VirtualBox, Hyper-V, WSL2, OpenVPN TAP/TUN.
func isVirtualIface(name string) bool {
	lower := strings.ToLower(name)
	// Linux-style prefixes
	for _, p := range []string{"vmnet", "vboxnet", "veth", "docker", "br-", "virbr"} {
		if strings.HasPrefix(lower, p) {
			return true
		}
	}
	// Windows adapter name substrings
	for _, s := range []string{"vmware", "virtualbox", "hyper-v", "wsl", "vethernet", "tap adapter", "tun driver", "openvpn"} {
		if strings.Contains(lower, s) {
			return true
		}
	}
	return false
}

func isInvalidGW(gw string) bool {
	return gw == "" || gw == "0.0.0.0" || gw == "On-link"
}

func isRFC1918(ip net.IP) bool {
	private := []string{"10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"}
	for _, cidr := range private {
		_, block, _ := net.ParseCIDR(cidr)
		if block.Contains(ip) {
			return true
		}
	}
	return false
}

// guessGateway returns the .1 address of the given network IP.
func guessGateway(networkIP net.IP) string {
	ip := make(net.IP, 4)
	copy(ip, networkIP.To4())
	ip[3] = 1
	return ip.String()
}

// nameForCIDR generates a short network name from the CIDR.
func nameForCIDR(cidr, localIP string) string {
	ip := net.ParseIP(localIP).To4()
	if ip == nil {
		return "net"
	}
	// Use third octet for 10.x.y.z or second for 192.168.y.z to make names unique
	switch {
	case ip[0] == 10:
		return fmt.Sprintf("vlan%d", ip[2])
	case ip[0] == 172:
		return fmt.Sprintf("net%d", ip[1])
	default: // 192.168.x.x
		return fmt.Sprintf("net%d", ip[2])
	}
}

type initSpecNetwork struct {
	Name    string `yaml:"name"`
	CIDR    string `yaml:"cidr"`
	Gateway string `yaml:"gateway"`
	Zone    string `yaml:"zone"`
}

type initSpecAssertion struct {
	Type           string  `yaml:"type"`
	Network        string  `yaml:"network,omitempty"`
	Target         string  `yaml:"target,omitempty"`
	Query          string  `yaml:"query,omitempty"`
	Server         string  `yaml:"server,omitempty"`
	ExpectHostsMin *int    `yaml:"expect_hosts_min,omitempty"`
	ExpectHostsMax *int    `yaml:"expect_hosts_max,omitempty"`
	ExpectLatency  float64 `yaml:"expect_latency_ms,omitempty"`
	ExpectLoss     float64 `yaml:"expect_loss_pct,omitempty"`
	ScanMode       string  `yaml:"scan_mode,omitempty"`
}

type initSpec struct {
	Version    int                 `yaml:"version"`
	Site       string              `yaml:"site"`
	Networks   []initSpecNetwork   `yaml:"networks"`
	Policies   []interface{}       `yaml:"policies"`
	Assertions []initSpecAssertion `yaml:"assertions"`
}

func buildInitSpec(nets []initNet) initSpec {
	var networks []initSpecNetwork
	var assertions []initSpecAssertion

	for _, n := range nets {
		name := nameForCIDR(n.cidr, n.localIP)
		networks = append(networks, initSpecNetwork{
			Name:    name,
			CIDR:    n.cidr,
			Gateway: n.gateway,
			Zone:    name,
		})

		maxHosts := n.hosts + 20
		if maxHosts < 10 {
			maxHosts = 10
		}
		a := initSpecAssertion{
			Type:          "subnet_discovery",
			Network:       name,
			ExpectHostsMax: &maxHosts,
			ScanMode:      "normal",
		}
		if n.hosts > 0 {
			minHosts := 1
			a.ExpectHostsMin = &minHosts
		}
		assertions = append(assertions, a)

		assertions = append(assertions, initSpecAssertion{
			Type:          "network_health",
			Target:        n.gateway,
			ExpectLatency: 20,
			ExpectLoss:    0,
		})

		if !isVirtualIface(n.ifaceName) {
			assertions = append(assertions, initSpecAssertion{
				Type:   "dns_check",
				Query:  "google.com",
				Server: n.gateway,
			})
		}
	}

	siteName := "my-network"
	if len(nets) > 0 {
		parts := strings.Split(nets[0].localIP, ".")
		if len(parts) >= 2 {
			siteName = fmt.Sprintf("site-%s-%s", parts[0], parts[1])
		}
	}

	return initSpec{
		Version:    1,
		Site:       siteName,
		Networks:   networks,
		Policies:   []interface{}{},
		Assertions: assertions,
	}
}

func init() {
	initCmd.Flags().StringVar(&initOutput, "output", "", "Write generated spec to file (default: stdout)")
	rootCmd.AddCommand(initCmd)
}
