package cli

import (
	"context"
	"fmt"
	"net"
	"os"
	"strings"
	"time"

	"github.com/spf13/cobra"
	"github.com/velasco-jp/nyx/internal/backends/nmap"
	"github.com/velasco-jp/nyx/internal/backends/system"
	"gopkg.in/yaml.v3"
)

var initOutput string

var initCmd = &cobra.Command{
	Use:   "init",
	Short: "Auto-detect your network and generate a starter spec",
	Long: `Discover local interfaces, RFC1918 routes, and live hosts via nmap ping sweep,
then write a nyx.yaml spec you can customize.`,
	Example: `  nyx init
  nyx init --output mynet.yaml`,
	RunE: func(cmd *cobra.Command, args []string) error {
		if err := nmap.CheckAvailable(); err != nil {
			return fmt.Errorf("nyx init requires nmap: %w", err)
		}

		out := os.Stdout
		if initOutput != "" {
			f, err := os.Create(initOutput)
			if err != nil {
				return fmt.Errorf("creating output file: %w", err)
			}
			defer f.Close()
			out = f
		}

		// First Contact: orient the user to where we are
		brief := GetEnvironmentBriefing(nil)
		fmt.Fprint(os.Stderr, RenderEnvironmentBriefing(brief))

		// Respect --interface if specified
		selectedIface := GetSelectedInterface()
		if selectedIface != "" {
			// Validate the interface exists
			ifaces, _ := net.Interfaces()
			ifaceFound := false
			for _, iface := range ifaces {
				if iface.Name == selectedIface {
					ifaceFound = true
					break
				}
			}
			if !ifaceFound {
				return fmt.Errorf("interface %q not found — run 'nyx interfaces' to see available adapters", selectedIface)
			}
			fmt.Fprintf(os.Stderr, "You specified --interface %s, so I'll only scan networks reachable from that adapter.\n", selectedIface)
		}

		fmt.Fprintln(os.Stderr, "Okay, now let me scan those networks and build a starter spec for you...")
		fmt.Fprintln(os.Stderr, "Detecting local networks...")
		localCIDRs, err := detectLocalCIDRs(selectedIface)
		if err != nil {
			return fmt.Errorf("detecting interfaces: %w", err)
		}
		if len(localCIDRs) == 0 {
			return fmt.Errorf("no RFC1918 interfaces found — are you connected to a network?")
		}

		var nets []initNet
		dur, _ := time.ParseDuration(timeout)
		if dur == 0 {
			dur = 300 * time.Second
		}

		for _, c := range localCIDRs {
			fmt.Fprintf(os.Stderr, "Scanning %s — this may take a moment...\n", c.cidr)
			ctx, cancel := context.WithTimeout(context.Background(), dur)
			result, err := nmap.DiscoverWithOptions(ctx, c.cidr, nmap.PoliteScanOptions)
			cancel()

			hostCount := 0
			if err != nil {
				fmt.Fprintf(os.Stderr, "  scan failed: %v — continuing with 0 hosts\n", err)
			} else if result != nil {
				if v, ok := result.Observed["hosts_up"]; ok {
					switch n := v.(type) {
					case int:
						hostCount = n
					case float64:
						hostCount = int(n)
					}
				}
			}

			nets = append(nets, initNet{
				cidr:      c.cidr,
				gateway:   c.gateway,
				localIP:   c.localIP,
				hosts:     hostCount,
				ifaceName: c.ifaceName,
			})
			fmt.Fprintf(os.Stderr, "  found %d host(s) up\n", hostCount)
		}

		// Build spec YAML
		generatedSpec := buildInitSpec(nets)
		data, err := yaml.Marshal(generatedSpec)
		if err != nil {
			return fmt.Errorf("marshalling spec: %w", err)
		}

		full := "# Generated by nyx init — customize networks, policies, probes, and assertions to match your intent.\n# The policies and probes below are suggestions based on detected network segments.\n# Review them, then run: nyx audit --spec <this-file>.yaml\n\n" + string(data)
		n, err := fmt.Fprint(out, full)
		if err != nil {
			return fmt.Errorf("writing spec: %w", err)
		}
		if n != len(full) {
			return fmt.Errorf("incomplete write: wrote %d of %d bytes", n, len(full))
		}

		// Summary of what was found
		totalHosts := 0
		for _, n := range nets {
			totalHosts += n.hosts
		}

		fmt.Fprintf(os.Stderr, "\nI found %d network(s) with %d host(s) total.\n", len(nets), totalHosts)
		fmt.Fprintf(os.Stderr, "Generated %d assertion(s), %d policy(ies), and %d probe(s) as a starting point.\n",
			len(generatedSpec.Assertions), len(generatedSpec.Policies), len(generatedSpec.Probes))

		if initOutput != "" {
			fmt.Fprintf(os.Stderr, "Wrote starter spec to %s\n", initOutput)
			fmt.Fprintf(os.Stderr, "Review it, customize it, then run: nyx audit --spec %s\n", initOutput)
		} else {
			fmt.Fprintln(os.Stderr, "\nThat's your starter spec above. Save it to a file, customize it, then run:")
			fmt.Fprintln(os.Stderr, "  nyx audit --spec <your-file>.yaml")
		}
		return nil
	},
}

type initNet struct {
	cidr      string
	gateway   string
	localIP   string
	hosts     int
	ifaceName string
}

type localCIDR struct {
	cidr      string
	gateway   string
	localIP   string
	ifaceName string
}

// detectLocalCIDRs finds RFC1918 subnets the local machine has addresses in,
// using the routing table to find real gateways instead of guessing .1.
// If interfaceName is non-empty, only that interface is considered.
func detectLocalCIDRs(interfaceName string) ([]localCIDR, error) {
	ifaces, err := net.Interfaces()
	if err != nil {
		return nil, err
	}

	// Build a map of subnet CIDR → gateway from the routing table.
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	routeGateways := map[string]string{}
	defaultGW := ""
	defaultGWMetric := -1
	if routes, err := system.GetRoutes(ctx); err != nil {
		fmt.Fprintf(os.Stderr, "warning: could not read routing table: %v (gateway detection will use defaults)\n", err)
	} else {
		for _, r := range routes {
			if isInvalidGW(r.Gateway) {
				continue
			}
			if r.Destination == "default" {
				// Keep the lowest-metric default route as the primary gateway.
				if defaultGWMetric < 0 || r.Metric < defaultGWMetric {
					defaultGW = r.Gateway
					defaultGWMetric = r.Metric
				}
				continue
			}
			routeGateways[r.Destination] = r.Gateway
		}
	}

	seen := map[string]bool{}
	var results []localCIDR

	for _, iface := range ifaces {
		if iface.Flags&net.FlagUp == 0 || iface.Flags&net.FlagLoopback != 0 {
			continue
		}
		if interfaceName != "" && iface.Name != interfaceName {
			continue
		}
		addrs, err := iface.Addrs()
		if err != nil {
			fmt.Fprintf(os.Stderr, "warning: could not read addresses for %s: %v (skipping)\n", iface.Name, err)
			continue
		}
		for _, a := range addrs {
			ipNet, ok := a.(*net.IPNet)
			if !ok {
				continue
			}
			ip := ipNet.IP.To4()
			if ip == nil || !isRFC1918(ip) {
				continue
			}
			maskedIP := ip.Mask(ipNet.Mask)
			network := &net.IPNet{IP: maskedIP, Mask: ipNet.Mask}
			cidrStr := network.String()
			if seen[cidrStr] {
				continue
			}
			seen[cidrStr] = true

			// Use routing table gateway if known. For directly-connected subnets
			// the route table shows "On-link" as gateway, so check if the default
			// gateway falls within this subnet before falling back to .1.
			gw := routeGateways[cidrStr]
			if gw == "" && defaultGW != "" {
				if parsedGW := net.ParseIP(defaultGW); parsedGW != nil {
					if _, subnet, err := net.ParseCIDR(cidrStr); err == nil {
						if subnet.Contains(parsedGW) {
							gw = defaultGW
						}
					}
				}
			}
			if gw == "" {
				gw = guessGateway(maskedIP)
			}
			results = append(results, localCIDR{
				cidr:      cidrStr,
				gateway:   gw,
				localIP:   ip.String(),
				ifaceName: iface.Name,
			})
		}
	}
	return results, nil
}

// isVirtualIface returns true for host-only/NAT virtual adapters that have no
// real DNS server — VMware, VirtualBox, Hyper-V, WSL2, OpenVPN TAP/TUN.
func isVirtualIface(name string) bool {
	lower := strings.ToLower(name)
	// Linux-style prefixes
	for _, p := range []string{"vmnet", "vboxnet", "veth", "docker", "br-", "virbr"} {
		if strings.HasPrefix(lower, p) {
			return true
		}
	}
	// Windows adapter name substrings
	for _, s := range []string{"vmware", "virtualbox", "hyper-v", "wsl", "vethernet", "tap adapter", "tun driver", "openvpn"} {
		if strings.Contains(lower, s) {
			return true
		}
	}
	return false
}

func isInvalidGW(gw string) bool {
	if gw == "" || gw == "0.0.0.0" || gw == "On-link" {
		return true
	}
	return net.ParseIP(gw) == nil
}

func isRFC1918(ip net.IP) bool {
	private := []string{"10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"}
	for _, cidr := range private {
		_, block, _ := net.ParseCIDR(cidr)
		if block.Contains(ip) {
			return true
		}
	}
	return false
}

// guessGateway returns the .1 address of the given network IP.
func guessGateway(networkIP net.IP) string {
	ip := make(net.IP, 4)
	copy(ip, networkIP.To4())
	ip[3] = 1
	return ip.String()
}

// inferNetworkName tries to suggest a meaningful name based on network characteristics.
// It uses host count, network size, and common patterns to produce names like
// "lan", "iot", "guest", "servers", etc. rather than generic "net20".
func inferNetworkName(cidr string, hostCount int) string {
	_, netw, err := net.ParseCIDR(cidr)
	if err != nil {
		return "net"
	}

	// Calculate network size
	netBits, _ := netw.Mask.Size()
	networkSize := 1<<(32-netBits) - 2 // usable hosts

	// Very large networks (10.x.x.x/16 or bigger) are likely datacenter/cloud
	if networkSize > 10000 {
		return "infrastructure"
	}

	// Large networks with many hosts (server farms)
	if networkSize > 254 && hostCount > 50 {
		return "servers"
	}

	// Small networks (IoT, guest, etc.)
	if networkSize <= 14 {
		return "iot"
	}

	// Medium networks with few hosts — likely a guest or isolated segment
	if networkSize <= 254 && hostCount <= 5 && hostCount > 0 {
		return "guest"
	}

	// The network with the most hosts is likely the main LAN
	if hostCount > 20 {
		return "lan"
	}

	// Medium networks with moderate host count
	if hostCount > 10 {
		return "clients"
	}

	return "segment"
}

// nameForCIDR generates a network name, ensuring uniqueness across all networks.
// It first tries to infer a meaningful name, then falls back to CIDR-based naming.
func nameForCIDR(cidr, localIP string, hostCount int, usedNames map[string]bool) string {
	name := inferNetworkName(cidr, hostCount)
	if !usedNames[name] {
		usedNames[name] = true
		return name
	}

	// Name collision — append a number
	baseName := name
	counter := 2
	for usedNames[fmt.Sprintf("%s%d", baseName, counter)] {
		counter++
	}
	name = fmt.Sprintf("%s%d", baseName, counter)
	usedNames[name] = true
	return name
}

type initSpecNetwork struct {
	Name    string `yaml:"name"`
	CIDR    string `yaml:"cidr"`
	Gateway string `yaml:"gateway"`
	Zone    string `yaml:"zone"`
}

type initSpecAssertion struct {
	Type           string  `yaml:"type"`
	Network        string  `yaml:"network,omitempty"`
	Target         string  `yaml:"target,omitempty"`
	Query          string  `yaml:"query,omitempty"`
	Server         string  `yaml:"server,omitempty"`
	ExpectHostsMin *int    `yaml:"expect_hosts_min,omitempty"`
	ExpectHostsMax *int    `yaml:"expect_hosts_max,omitempty"`
	ExpectLatency  float64 `yaml:"expect_latency_ms,omitempty"`
	ExpectLoss     float64 `yaml:"expect_loss_pct,omitempty"`
	ScanMode       string  `yaml:"scan_mode,omitempty"`
}

type initSpec struct {
	Version    int                 `yaml:"version"`
	Site       string              `yaml:"site"`
	Networks   []initSpecNetwork   `yaml:"networks"`
	Probes     []interface{}       `yaml:"probes,omitempty"`
	Policies   []interface{}       `yaml:"policies"`
	Assertions []initSpecAssertion `yaml:"assertions"`
}

func buildInitSpec(nets []initNet) initSpec {
	var networks []initSpecNetwork
	var assertions []initSpecAssertion
	var policies []interface{}
	var probes []interface{}

	// Track used names to ensure uniqueness
	usedNames := map[string]bool{}

	// Determine which network is the runner's network (largest host count or first)
	runnerNet := ""
	maxHosts := 0
	for _, n := range nets {
		if n.hosts > maxHosts {
			maxHosts = n.hosts
			runnerNet = n.cidr
		}
	}

	for _, n := range nets {
		name := nameForCIDR(n.cidr, n.localIP, n.hosts, usedNames)

		// Infer zone from name: lan -> clients, iot -> iot, servers -> servers, etc.
		zone := name
		switch name {
		case "lan", "clients":
			zone = "clients"
		case "guest":
			zone = "guest"
		case "iot":
			zone = "iot"
		case "servers":
			zone = "servers"
		}

		networks = append(networks, initSpecNetwork{
			Name:    name,
			CIDR:    n.cidr,
			Gateway: n.gateway,
			Zone:    zone,
		})

		maxH := n.hosts + 20
		if maxH < 10 {
			maxH = 10
		}
		a := initSpecAssertion{
			Type:          "subnet_discovery",
			Network:       name,
			ExpectHostsMax: &maxH,
			ScanMode:      "normal",
		}
		if n.hosts > 0 {
			minHosts := 1
			a.ExpectHostsMin = &minHosts
		}
		assertions = append(assertions, a)

		assertions = append(assertions, initSpecAssertion{
			Type:          "network_health",
			Target:        n.gateway,
			ExpectLatency: 20,
			ExpectLoss:    0,
		})

		if !isVirtualIface(n.ifaceName) {
			assertions = append(assertions, initSpecAssertion{
				Type:   "dns_check",
				Query:  "google.com",
				Server: n.gateway,
			})
		}
	}

	// Generate default isolation policies based on detected zones.
	// The heuristic: iot and guest should be isolated from clients/servers.
	// This gives a meaningful starting point rather than an empty policies list.
	policyCounter := 0
	for _, n := range networks {
		sourceZone := n.Zone
		// IOT and guest should not reach clients or servers
		if sourceZone == "iot" || sourceZone == "guest" {
			for _, target := range networks {
				targetZone := target.Zone
				if targetZone == "clients" || targetZone == "servers" {
					policyCounter++
					policies = append(policies, map[string]interface{}{
						"name":   fmt.Sprintf("isolate-%s-from-%s", sourceZone, targetZone),
						"from":   sourceZone,
						"to":     targetZone,
						"action": "deny",
					})
				}
			}
		}
	}

	// Suggest probes for networks that aren't the runner's network.
	// Probes let checks run from the correct vantage point.
	probeCounter := 0
	for _, n := range networks {
		if n.CIDR == runnerNet {
			continue // No probe needed for the runner's own network
		}
		probeCounter++
		probes = append(probes, map[string]interface{}{
			"name": fmt.Sprintf("%s-probe", n.Name),
			"host": n.Gateway,
			"user": "<your-user>",
			"vlan": n.Zone,
		})
	}

	siteName := "my-network"
	if len(nets) > 0 {
		parts := strings.Split(nets[0].localIP, ".")
		if len(parts) >= 2 {
			siteName = fmt.Sprintf("site-%s-%s", parts[0], parts[1])
		}
	}

	return initSpec{
		Version:    1,
		Site:       siteName,
		Networks:   networks,
		Policies:   policies,
		Assertions: assertions,
		Probes:     probes,
	}
}

func init() {
	initCmd.Flags().StringVar(&initOutput, "output", "", "Write generated spec to file (default: stdout)")
	rootCmd.AddCommand(initCmd)
}
