package cli

import (
	"context"
	"fmt"
	"os"
	"time"

	"github.com/spf13/cobra"
	"github.com/velasco-jp/nyx/internal/audit"
	"github.com/velasco-jp/nyx/internal/backends/omada"
	"github.com/velasco-jp/nyx/internal/report"
	"gopkg.in/yaml.v3"
)

var (
	omadaController string
	omadaUsername   string
	omadaPassword   string
	omadaSite       string
	omadaOutFile    string
	omadaDebug      bool
)

var omadaCmd = &cobra.Command{
	Use:   "omada",
	Short: "Omada SDN controller integration",
	Long:  "Commands for importing configuration and running audits against an Omada SDN controller.",
}

// -----------------------------------------------------------------------
// omada import
// -----------------------------------------------------------------------

var omadaImportCmd = &cobra.Command{
	Use:   "import",
	Short: "Import network topology from Omada controller and generate a spec",
	Long: `Connects to your Omada controller, reads VLANs, ACL rules, and
connected clients, then generates a nyx spec YAML file.

Credentials can be supplied via flags or environment variables:
  OMADA_USERNAME  — controller admin username
  OMADA_PASSWORD  — controller admin password
  OMADA_HOST      — controller IP or hostname (overrides --controller)`,
	Example: `  nyx omada import --controller 192.168.0.253 --out homelab.yaml
  OMADA_USERNAME=admin OMADA_PASSWORD=secret nyx omada import --controller 192.168.0.253`,
	RunE: func(cmd *cobra.Command, args []string) error {
		host, user, pass, err := resolveOmadaCreds(omadaController, omadaUsername, omadaPassword)
		if err != nil {
			return err
		}

		dur, parseErr := time.ParseDuration(timeout)
		if parseErr != nil {
			dur = 30 * time.Second
		}
		ctx, cancel := context.WithTimeout(context.Background(), dur)
		defer cancel()

		fmt.Fprintf(os.Stderr, "Connecting to Omada controller at %s...\n", host)

		result, err := omada.ImportSpec(ctx, host, user, pass, omadaSite, omadaDebug)
		if err != nil {
			return fmt.Errorf("import failed: %w", err)
		}

		// Print warnings to stderr so they don't pollute the YAML output
		for _, w := range result.Warnings {
			fmt.Fprintf(os.Stderr, "Warning: %s\n", w)
		}

		fmt.Fprintf(os.Stderr, "Imported from site %q: %d networks, %d ACL rules, %d connected clients\n",
			result.Site.Name, result.NetworkCount, result.ACLRuleCount, result.ClientCount)

		// Serialise spec to YAML
		specYAML, err := yaml.Marshal(result.Spec)
		if err != nil {
			return fmt.Errorf("serializing spec: %w", err)
		}

		header := fmt.Sprintf("# Generated by nyx omada import\n# Controller: %s  Site: %s\n# Controller version: %s\n\n",
			host, result.Site.Name, result.ControllerVersion)

		out := []byte(header)
		out = append(out, specYAML...)

		if omadaOutFile != "" {
			if err := os.WriteFile(omadaOutFile, out, 0644); err != nil {
				return fmt.Errorf("writing spec to %s: %w", omadaOutFile, err)
			}
			fmt.Fprintf(os.Stderr, "Spec written to %s\n", omadaOutFile)
		} else {
			fmt.Print(string(out))
		}
		return nil
	},
}

// -----------------------------------------------------------------------
// omada check
// -----------------------------------------------------------------------

var omadaCheckCmd = &cobra.Command{
	Use:   "check",
	Short: "Import from Omada controller and immediately run a live audit",
	Long: `Imports network topology from the Omada controller, then runs a live
audit against your network to verify the actual behaviour matches the
configured intent.

This is equivalent to:
  nyx omada import --controller <host> | nyx audit --spec -

Credentials via flags or env vars (OMADA_USERNAME, OMADA_PASSWORD, OMADA_HOST).`,
	Example: `  nyx omada check --controller 192.168.0.253
  nyx omada check --controller 192.168.0.253 --json`,
	RunE: func(cmd *cobra.Command, args []string) error {
		host, user, pass, err := resolveOmadaCreds(omadaController, omadaUsername, omadaPassword)
		if err != nil {
			return err
		}

		dur, parseErr := time.ParseDuration(timeout)
		if parseErr != nil {
			dur = 300 * time.Second
		}
		ctx, cancel := context.WithTimeout(context.Background(), dur)
		defer cancel()

		fmt.Fprintf(os.Stderr, "Connecting to Omada controller at %s...\n", host)

		result, err := omada.ImportSpec(ctx, host, user, pass, omadaSite, omadaDebug)
		if err != nil {
			return fmt.Errorf("import failed: %w", err)
		}

		for _, w := range result.Warnings {
			fmt.Fprintf(os.Stderr, "Warning: %s\n", w)
		}

		fmt.Fprintf(os.Stderr, "Running audit for site %q (%d networks, %d assertions)...\n",
			result.Site.Name, result.NetworkCount, len(result.Spec.Assertions))

		engine := audit.NewEngine(result.Spec)
		auditReport, err := engine.Run(ctx)
		if err != nil {
			return fmt.Errorf("audit failed: %w", err)
		}

		w, err := getWriter()
		if err != nil {
			return err
		}
		if outputPath != "" {
			defer w.Close()
		}

		if jsonOutput {
			return report.RenderJSON(w, auditReport)
		}
		report.RenderHuman(w, auditReport)
		return nil
	},
}

// -----------------------------------------------------------------------
// omada info
// -----------------------------------------------------------------------

var omadaInfoCmd = &cobra.Command{
	Use:   "info",
	Short: "Show Omada controller version and connection info (no credentials required)",
	Example: `  nyx omada info --controller 192.168.0.253`,
	RunE: func(cmd *cobra.Command, args []string) error {
		host := omadaController
		if h := os.Getenv("OMADA_HOST"); h != "" && host == "" {
			host = h
		}
		if host == "" {
			return fmt.Errorf("--controller is required (or set OMADA_HOST)")
		}

		ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
		defer cancel()

		client, err := omada.NewClient(ctx, host)
		if err != nil {
			return fmt.Errorf("connecting to controller: %w", err)
		}

		info := client.Info()
		fmt.Printf("Controller : %s\n", host)
		fmt.Printf("Version    : %s\n", info.ControllerVer)
		fmt.Printf("API version: v%s\n", info.APIVer)
		fmt.Printf("OmadaCID   : %s\n", info.OmadaCID)
		fmt.Printf("Configured : %v\n", info.Configured)
		return nil
	},
}

// -----------------------------------------------------------------------
// Helpers
// -----------------------------------------------------------------------

// resolveOmadaCreds returns the controller host, username, and password,
// preferring explicit flags over environment variables.
// Credentials are NEVER printed or logged.
func resolveOmadaCreds(flagHost, flagUser, flagPass string) (host, user, pass string, err error) {
	host = flagHost
	if h := os.Getenv("OMADA_HOST"); h != "" && host == "" {
		host = h
	}
	if host == "" {
		return "", "", "", fmt.Errorf("--controller is required (or set OMADA_HOST)")
	}

	user = flagUser
	if u := os.Getenv("OMADA_USERNAME"); u != "" && user == "" {
		user = u
	}
	if user == "" {
		return "", "", "", fmt.Errorf("--username is required (or set OMADA_USERNAME)")
	}

	pass = flagPass
	if p := os.Getenv("OMADA_PASSWORD"); p != "" && pass == "" {
		pass = p
	}
	if pass == "" {
		return "", "", "", fmt.Errorf("--password is required (or set OMADA_PASSWORD)")
	}

	return host, user, pass, nil
}

func init() {
	// Shared flags across omada subcommands
	for _, cmd := range []*cobra.Command{omadaImportCmd, omadaCheckCmd, omadaInfoCmd} {
		cmd.Flags().StringVar(&omadaController, "controller", "", "Omada controller IP or hostname")
		cmd.Flags().StringVar(&omadaSite, "site", "", "Omada site name (defaults to first site if omitted)")
	}
	for _, cmd := range []*cobra.Command{omadaImportCmd, omadaCheckCmd} {
		cmd.Flags().StringVar(&omadaUsername, "username", "", "Controller admin username (or set OMADA_USERNAME)")
		cmd.Flags().StringVar(&omadaPassword, "password", "", "Controller admin password (or set OMADA_PASSWORD)")
		cmd.Flags().BoolVar(&omadaDebug, "debug", false, "Print raw API responses to stderr for troubleshooting")
	}
	omadaImportCmd.Flags().StringVar(&omadaOutFile, "out", "", "Write spec YAML to this file (default: stdout)")

	omadaCmd.AddCommand(omadaImportCmd)
	omadaCmd.AddCommand(omadaCheckCmd)
	omadaCmd.AddCommand(omadaInfoCmd)
}
